calendarAPP/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calendar/', include('happenings.urls', namespace='calendar')),
]

happenings/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from . import views


urlpatterns = [
    url(r'^$', views.EventMonthView.as_view(), name='list'),
    url(r'^month/shift/$', views.EventMonthView.as_view(), name='month_shift'),
    url(r'^event-list/shift/$', views.EventMonthView.as_view(), name='event_list_shift'),
    url(r'^cal-and-list/shift/$', views.EventMonthView.as_view(), name='cal_and_list_shift'),
    url(r'^event/(?P<pk>[\w-]+)/$', views.EventDetailView.as_view(), name='detail'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2}|\d{1})/$', views.EventMonthView.as_view(), name='list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2}|\d{1})/(?P<day>\d{2}|\d{1})/$', views.EventDayView.as_view(), name='day_list'),
    url(r'^createevent/$', views.createEvent, name = 'createevent'),
    url(r'^editevent/(?P<pk>[\w-]+)/$', views.editEvent, name = 'editevent'),
    url(r'^event/(?P<pk>[\w-]+)/delete/$', views.cancelEvent, name='cancel'),
]

happenings/forms.py
from django import forms
from django.forms import ModelForm
from .models import Event
from django.db import models
from django.utils import timezone
import sys

class EventForm(ModelForm):
    def clean_start_onlydate(self):
        if(self.data['start_onlydate'] == ""):
            raise forms.ValidationError("Enter valid start date.")
        else:
            return self.cleaned_data['start_onlydate']

    def clean_start_onlytime(self):
        if(self.data['start_onlytime'] == ""):
            raise forms.ValidationError("Enter valid start time.")
        else:
            return self.cleaned_data['start_onlytime']

    def clean_end_onlydate(self):
        if(self.data['end_onlydate'] == ""):
            raise froms.ValidationError("Enter valid end date.")
        else:
             return self.cleaned_data['end_onlydate']

    def clean_end_onlytime(self):
        if(self.data['end_onlytime'] == ""):
            raise froms.ValidationError("Enter valid end time.")
        else:
            return self.cleaned_data['end_onlytime']

    def clean_start_date(self):
        data = timezone.now()
        if self.data['start_onlydate'] == "" or self.data['start_onlytime'] == "":
            if(self.data['start_onlydate'] == ""):
                raise forms.ValidationError("Enter valid start date.")
            if(self.data['start_onlytime'] == ""):
                raise forms.ValidationError("Enter valid start time.")
        else:
            print("Warning: ", self.data['start_onlydate'], file=sys.stderr)
            print("Warning: ", self.data['start_onlytime'], file=sys.stderr)
            myDate = self.cleaned_data['start_onlydate']
            myTime = self.cleaned_data['start_onlytime']
            data = data.replace(year=myDate.year)
            data = data.replace(month=myDate.month)
            data = data.replace(day=myDate.day)
            data = data.replace(hour=myTime.hour)
            data = data.replace(minute=myTime.minute)
            data = data.replace(second=myTime.second)
        return data

    def clean_end_date(self):
        data = timezone.now()
        if self.data['end_onlydate'] == "" or self.data['end_onlytime'] == "":
            if(self.data['start_onlydate'] == ""):
                raise forms.ValidationError("Enter valid end date.")
            if(self.data['start_onlytime'] == ""):
                raise forms.ValidationError("Enter valid end time.")
        else:
            print("Warning: ", self.data['end_onlydate'], file=sys.stderr)
            myDate = self.cleaned_data['end_onlydate']
            myTime = self.cleaned_data['end_onlytime']
            data = data.replace(year=myDate.year)
            data = data.replace(month=myDate.month)
            data = data.replace(day=myDate.day)
            data = data.replace(hour=myTime.hour)
            data = data.replace(minute=myTime.minute)
            data = data.replace(second=myTime.second)
        return data
    
    class Meta:
        model = Event
        fields =['title', 'start_onlytime', 'end_onlytime', 'start_onlydate', 'end_onlydate', 'start_date', 'end_date', 'description', 'phone', 'address_1', 'address_2', 'city', 'state', 'zipcode', 'sales_order', 'pick', 'weight', 'pallet', 'driver']
        widgets = {
            'start_onlytime' : forms.TimeInput(attrs={'type':'time'}),
            'end_onlytime' : forms.TimeInput(attrs={'type':'time'}),
            'start_onlydate' : forms.DateInput(attrs={'type':'date'}),
            'end_onlydate' : forms.DateInput(attrs={'type':'date'})
        }

happenings/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import sys
from django import forms

# python lib:
from datetime import date, timedelta
from .forms import EventForm
import datetime

# django:
from django.views.generic import ListView, DetailView
from django.conf import settings
from django.shortcuts import get_object_or_404, render
from django.utils.dates import MONTHS_ALT
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

# thirdparties:
import six

# happenings:
from .models import Event
from happenings.utils.displays import month_display, day_display
from happenings.utils.next_event import get_next_event
from happenings.utils.mixins import JSONResponseMixin
from happenings.utils import common as c


CALENDAR_LOCALE = getattr(settings, 'CALENDAR_LOCALE', 'en_US.utf8')


class GenericEventView(JSONResponseMixin, ListView):
    model = Event

    def render_to_response(self, context, **kwargs):
        if self.request.is_ajax():
            return self.render_to_json_response(context, **kwargs)
        return super(GenericEventView, self).render_to_response(
            context, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super(GenericEventView, self).get_context_data(**kwargs)

        self.net, self.category, self.tag = c.get_net_category_tag(
            self.request
        )

        if self.category is not None:
            context['cal_category'] = self.category
        if self.tag is not None:
            context['cal_tag'] = self.tag
        return context


class EventMonthView(GenericEventView):
    template_name = 'happenings/event_month_list.html'

    def get_year_and_month(self, net, qs, **kwargs):
        """
        Get the year and month. First tries from kwargs, then from
        querystrings. If none, or if cal_ignore qs is specified,
        sets year and month to this year and this month.
        """
        now = c.get_now()
        year = now.year
        month = now.month + net
        month_orig = None

        if 'cal_ignore=true' not in qs:
            if 'year' and 'month' in self.kwargs:  # try kwargs
                year, month_orig = map(
                    int, (self.kwargs['year'], self.kwargs['month'])
                )
                month = month_orig + net
            else:
                try:  # try querystring
                    year = int(self.request.GET['cal_year'])
                    month_orig = int(self.request.GET['cal_month'])
                    month = month_orig + net
                except Exception:
                    pass
        # return the year and month, and any errors that may have occurred do
        # to an invalid month/year being given.
        return c.clean_year_month(year, month, month_orig)

    def get_month_events(self, *args, **kwargs):
        return Event.objects.all_month_events(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EventMonthView, self).get_context_data(**kwargs)

        qs = self.request.META['QUERY_STRING']

        year, month, error = self.get_year_and_month(self.net, qs)

        mini = True if 'cal_mini=true' in qs else False

        # get any querystrings that are not next/prev/year/month
        if qs:
            qs = c.get_qs(qs)

        # add a dict containing the year, month, and month name to the context
        current = dict(
            year=year, month_num=month, month=MONTHS_ALT[month][:3]
        )
        context['current'] = current

        display_month = MONTHS_ALT[month]

        if isinstance(display_month, six.binary_type):
            display_month = display_month.decode('utf-8')

        context['month_and_year'] = u"%(month)s, %(year)d" % (
            {'month': display_month, 'year': year}
        )

        if error:  # send any year/month errors
            context['cal_error'] = error

        # List enables sorting. As far as I can tell, .order_by() can't be used
        # here because we need it ordered by l_start_date.hour (simply ordering
        # by start_date won't work). The only alternative I've found is to use
        # extra(), but this would likely require different statements for
        # different databases...
        all_month_events = list(self.get_month_events(
            year, month, self.category, self.tag, loc=True, cncl=True
        ))

        all_month_events.sort(key=lambda x: x.l_start_date.hour)

        start_day = getattr(settings, "CALENDAR_START_DAY", 0)
        context['calendar'] = month_display(
            year, month, all_month_events, start_day, self.net, qs, mini,
            request=self.request,
        )

        context['show_events'] = False
        if getattr(settings, "CALENDAR_SHOW_LIST", False):
            context['show_events'] = True
            context['events'] = c.order_events(all_month_events, d=True) \
                if self.request.is_ajax() else c.order_events(all_month_events)

        return context


class EventDayView(GenericEventView):
    template_name = 'happenings/event_day_list.html'

    def check_for_cancelled_events(self, d):
        """Check if any events are cancelled on the given date 'd'."""
        for event in self.events:
            for cn in event.cancellations.all():
                if cn.date == d:
                    event.title += ' (CANCELLED)'

    def get_month_events(self, *args, **kwargs):
        return Event.objects.all_month_events(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EventDayView, self).get_context_data(**kwargs)

        kw = self.kwargs
        y, m, d = map(int, (kw['year'], kw['month'], kw['day']))
        year, month, day, error = c.clean_year_month_day(y, m, d, self.net)

        if error:
            context['cal_error'] = error

        # Note that we don't prefetch 'cancellations' because they will be
        # prefetched later (in day_display in displays.py)
        all_month_events = self.get_month_events(
            year, month, self.category, self.tag
        )

        self.events = day_display(
            year, month, all_month_events, day
        )

        self.check_for_cancelled_events(d=date(year, month, day))
        context['events'] = self.events

        display_month = MONTHS_ALT[month]
        if isinstance(display_month, six.binary_type):
            display_month = display_month.decode('utf-8')

        context['month'] = display_month
        context['month_num'] = month
        context['year'] = year
        context['day'] = day
        context['month_day_year'] = u"%(month)s %(day)d, %(year)d" % (
            {'month': display_month, 'day': day, 'year': year}
        )

        # for use in the template to build next & prev querystrings
        context['next'], context['prev'] = c.get_next_and_prev(self.net)
        return context


class EventDetailView(DetailView):
    model = Event
    context_object_name = 'event'

    def get_object(self):
        return get_object_or_404(
            Event.objects.prefetch_related(
                'location', 'categories', 'tags', 'cancellations'
            ),
            pk=self.kwargs['pk']
        )

    def get_cncl_days(self):
        now = c.get_now()
        cncl = self.object.cancellations.all()
        return [(x.date, x.reason) for x in cncl if x.date >= now.date()]

    def check_cncl(self, d):
        cncl = self.object.cancellations.all()
        return True if [x for x in cncl if x.date == d] else False

    def get_context_data(self, **kwargs):
        now = c.get_now()
        context = super(EventDetailView, self).get_context_data(**kwargs)
        e = self.object

        for choice in Event.REPEAT_CHOICES:
            if choice[0] == e.repeat:
                context['repeat'] = choice[1]

        context['cncl_days'] = self.get_cncl_days()

        event = [e]  # event needs to be an iterable, see get_next_event()
        if not e.repeats('NEVER'):  # event is ongoing; get next occurrence
            if e.will_occur(now):
                year, month, day = get_next_event(event, now)
                next_event = date(year, month, day)
                context['next_event'] = date(year, month, day)
                context['next_or_prev_cncl'] = self.check_cncl(next_event)
            else:  # event is finished repeating; get last occurrence
                end = e.end_repeat
                last_event = end
                if e.repeats('WEEKDAY'):
                    year, month, day = c.check_weekday(
                        end.year, end.month, end.day, reverse=True
                    )
                    last_event = date(year, month, day)
                context['last_event'] = last_event
                context['next_or_prev_cncl'] = self.check_cncl(last_event)
        else:
            if e.is_chunk():
                # list of days for single-day event chunk
                context['event_days'] = (  # list comp
                    (e.l_start_date + timedelta(days=x))
                    for x in range(e.start_end_diff + 1)
                )
            else:
                # let template know if this single-day, non-repeating event is
                # cancelled
                context['this_cncl'] = self.check_cncl(e.l_start_date.date())
        return context

def warning(*objs):
    print("WARNING: ", *objs, file=sys.stderr)

def createEvent(request):
    if request.method == 'POST':
        print("Test 1")
        form = EventForm(request.POST)
        if form.is_valid():
            print("Test 2")
            warning("before", form.cleaned_data['start_date'])
            warning("after", form.cleaned_data['start_date'])
            form.save()
            warning("after save", form.cleaned_data['start_date'])
            return HttpResponseRedirect(reverse('calendar:month_shift'))
        else:
            print("Test 3")
            print('Form errors', form.errors)
            form = EventForm()

happenings/templates/happenings/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Event Calendar{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'happenings/css/calendar.css' %}">

    {% block extra_css %}{% endblock extra_css %}

</head>

<body>

{% block content %}{% endblock content %}

<script src="{% static 'happenings/js/calendar.js' %}"></script>

{% block extra_js %}{% endblock extra_js %}

</body>

</html>

happenings/templates/happenings/cancel.html
<p>deleted<p>

happenings/templates/happenings/createevent.html
<head> 
	<meta charset = "utf-8">
	<title>Add Delivery</title>
</head>

<script type="text/javascript">
	function back()
	{
		location.href = '{% url "calendar:month_shift" %}';
	}
</script>

<style>
.hidden
{
	visibility: hidden;
}

.formTable
{
	text-align: left;
	display: inline-block;
}
</style>


<button type = "button" onClick = "back()"> Back to Calendar </button>

<h1>Add Delivery</h1>


<form action = "{% url 'calendar:createevent' %}" method="post">
	{% csrf_token %}
	{{ form.non_field_errors }}

	<table class = "formTable"><tbody>
		{{ form.title.errors }}
		<tr>
			<td>Customer:</td>
			<td>{{ form.title }}</td>
		</tr>
	</tbody>
	</table>
	
	<h2>Delivery Description</h2>
	<hr>

	{{ form.sales_order.errors }}
	{{ form.sales_order.label_tag }}
	{{ form.sales_order }}
	<br>
	<br>			
	
	{{ form.pick.errors }}
	{{ form.pick.label_tag }}
	{{ form.pick }}
	<br>
	<br>	
					
	{{ form.weight.errors }}
	{{ form.weight.label_tag }}
	{{ form.weight }}
	<br>
	<br>	
	
	{{ form.pallet.errors }}
	{{ form.pallet.label_tag }}
	{{ form.pallet }}
	<br>
	<br>

	{{ form.driver.errors }}	
	{{ form.driver.label_tag }}
	{{ form.driver }}
	
	<div class="hidden">
		{{ form.start_date }}
		{{ form.end_date }}
	</div>

	<h2>Time and Date</h2>
	<hr>
	<table class="formTable"<tbody>
		{{ form.start_onlytime.errors }}
		<tr>
			<td>{{ form.start_onlytime.label_tag }}</td>
			<td>{{ form.start_onlytime }}</td>
		</tr>
		{{ form.end_onlytime.errors }}
		<tr>
			<td>{{ form.end_onlytime.label_tag }}</td>
			<td>{{ form.end_onlytime }}</td>
		</tr>
		{{ form.start_onlydate.errors }}
		<tr>
			<td>{{ form.start_onlydate.label_tag }}</td>
			<td>{{ form.start_onlydate }}</td>
		</tr>
		{{ form.end_onlydate.errors }}
		<tr>
			<td>{{ form.end_onlydate.label_tag }}</td>
			<td>{{ form.end_onlydate }}</td>
		</tr>
	</tbody></table>

	<h2>Customer Info</h2>
	<hr>

	{{ form.phone.errors }}
	{{ form.phone.label_tag }}
	{{ form.phone }}
	<br>
	<br>

	{{ form.address_1.errors }}
	{{ form.address_1.label_tag }}
	{{ form.address_1 }}
	<br>
	<br>
			
	{{ form.address_2.errors }}
	{{ form.address_2.label_tag }}
	{{ form.address_2 }}
	<br>
	<br>
		
	{{ form.city.errors }}
	{{ form.city.label_tag }}
	{{ form.city }}
	<br>
	<br>
	
	{{ form.state.errors }}
	{{ form.state.label_tag }}
	{{ form.state }}
	<br>
	<br>
			
	{{ form.zipcode.errors }}
	{{ form.zipcode.label_tag }}
	{{ form.zipcode }}

	<h2>Additional Info</h2>
	<hr>
	{{ form.description.errors }}
	{{ form.description }}
	<br>

	<input type="submit" value="Submit" />
	<button type="button" onClick='back();'>Cancel</button>
</form>

happenings/templates/happenings/editevent.html
<head>
	<title>Edit Delivery</title>
	<script type="text/javascript">
		function goBack()
		{
			location.href = '{% url "calendar:detail" pk=pk %}';
		}
	</script>
</head>
<style>
	h1.visible
	{
		visibility: visible
	}

	.hidden
	{
		visibility: hidden
	}
</style>

	
<h1>Edit Event</h1>
<form action="{% url 'calendar:editevent' pk=pk %}" method="post">
	{% csrf_token %}
	{{ form.non_field_errors }}
	<br>

	{{ form.title.errors }}
	Customer:
	{{ form.title }}

	<h2>Delivery Description</h2>
	<hr>

	{{ form.sales_order.errors }}
	{{ form.sales_order.label_tag }}
	{{ form.sales_order }}
	<br>
	<br>			
	
	{{ form.pick.errors }}
	{{ form.pick.label_tag }}
	{{ form.pick }}
	<br>
	<br>	
				
	{{ form.weight.errors }}
	{{ form.weight.label_tag }}
	{{ form.weight }}
	<br>
	<br>

	{{ form.pallet.errors }}
	{{ form.pallet.label_tag }}
	{{ form.pallet }}
	<br>
	<br>
	
	{{ form.driver.errors }}	
	{{ form.driver.label_tag }}
	{{ form.driver }}

	<div class="hidden">
	{{ form.start_date }}
	{{ form.end_date }}
	</div>
		
	
	<h2>Time and Date</h2>
	<hr>
	<table class="formTable"<tbody>
	{{ form.start_onlytime.errors }}
		<tr>
			<td>{{ form.start_onlytime.label_tag }}</td>
			<td>{{ form.start_onlytime }}</td>
		</tr>
		{{ form.end_onlytime.errors }}
		<tr>
			<td>{{ form.end_onlytime.label_tag }}</td>
			<td>{{ form.end_onlytime }}</td>
		</tr>
		{{ form.start_onlydate.errors }}
		<tr>
			<td>{{ form.start_onlydate.label_tag }}</td>
			<td>{{ form.start_onlydate }}</td>
		</tr>
		{{ form.end_onlydate.errors }}
		<tr>
			<td>{{ form.end_onlydate.label_tag }}</td>
			<td>{{ form.end_onlydate }}</td>
		</tr>
	</tbody></table>
	
		<!--
		<h2>Time and Date</h2>
		<hr>
		<p></p>
			
		{{ form.start_onlytime.errors }}
		{{ form.start_onlytime.label_tag }}
		{{ form.start_onlytime }}
		<br>	

		{{ form.end_onlytime.errors }}
		{{ form.end_onlytime.label_tag }}
		{{ form.end_onlytime }}
		<br>		

		{{ form.start_onlydate.errors }}
		{{ form.start_onlydate.label_tag }}
		{{ form.start_onlydate }}
		<br>		

		{{ form.end_onlydate.errors }}
		{{ form.end_onlydate.label_tag }}
		{{ form.end_onlydate }}
		-->
				
	<h2>Customer Info</h2>
	<hr>
		
	{{ form.phone.errors }}
	{{ form.phone.label_tag }}
	{{ form.phone }}
	<br>
	<br>

	{{ form.address_1.errors }}
	{{ form.address_1.label_tag }}
	{{ form.address_1 }}
	<br>
	<br>
		
	{{ form.address_2.errors }}
	{{ form.address_2.label_tag }}
	{{ form.address_2 }}
	<br>
	<br>
		
	{{ form.city.errors }}
	{{ form.city.label_tag }}
	{{ form.city }}
	<br>
	<br>
	
	{{ form.state.errors }}
	{{ form.state.label_tag }}
	{{ form.state }}
	<br>
	<br>
			
	{{ form.zipcode.errors }}
	{{ form.zipcode.label_tag }}
	{{ form.zipcode }}	
		
	<h2>Additional Info</h2>
	<hr>
	{{ form.description.errors }}
	{{ form.description }}
	<br>
	<br>

	<input type="submit" value="Submit" />
	<button type='button' onClick='goBack();'>Cancel</button>
</form>			

happenings/templates/happenings/event_day_list.html
{% extends 'happenings/middle.html' %}

{% load staticfiles i18n %}



{% block content %}


    {% if cal_error %}

        {{ cal_error }}

    {% endif %}


<script type="text/javascript">
    function back()
    {
	location.href = '{% url "calendar:list" %}{{ year }}/{{ month_num }}/';
    }

    function myCreateEvent() 
    {
  	location.href = '{% url "calendar:createevent" %}';     
    }

    function prevDay()
    {
 	location.href = '{{ request.path }}?cal_prev={{ prev }}';
    }

    function nextDay()
    {
 	location.href = '{{ request.path }}?cal_next={{ next }}';
    }

</script>

	<button type = "button" onClick="back()"> Back to Calendar </button>
    	<!--
    
    <a href="{% url "calendar:list" %}{{ year }}/{{ month_num }}/">

        &larr; {% trans "Back to calendar" %}
    </a>

	-->	

    
<h1>

        {% trans "Events" %}<br>

    {% if cal_category and cal_tag %}

            {% blocktrans with c=cal_category t=cal_tag %}

            in category <span id="cal-day-category">{{ c }}</span>
 
           with tag <span id="cal-day-tag">{{ t }}</span>

            {% endblocktrans %}

    {% elif cal_category %}

            {% blocktrans with c=cal_category t=cal_tag %}

            with category <span id="cal-day-category">{{ c }}</span>
 
           {% endblocktrans %}

    {% elif cal_tag %}

            {% blocktrans with c=cal_category t=cal_tag %}

            with tag = <span id="cal-day-tag">{{ t }}</span>

            {% endblocktrans %}

    {% endif %}

    </h1>

    
<h2>{% trans "For" %}
 
        <span id="cal-day-mo">{{ month }}</span>
 
        <span id="cal-day-day">{{ day }}</span>,
 
        <span id="cal-day-year">{{ year }}</span>

    </h2>

	<hr>
        
	<p><p><button type = "button" onClick = "myCreateEvent()"> Add Delivery </button>   	
	
	<br><br>
	<button type="button" onClick="prevDay()"> Prev Day </button>
	<button type="button" onClick="nextDay()"> Next Day </button>



    
<ul class="day-event-list">

        {% for event in events %}

            <li><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></li>

        {% empty %}

            {% trans "Oops.. No events!" %}

        {% endfor %}

    </ul>

    

{% endblock content %}

happenings/templates/happenings/event_detail.html
{% extends 'happenings/middle.html' %}

{% load staticfiles i18n %}



{% block content %}


	<script type="text/javascript">
		function myEditEvent()
		{
			location.href = "/calendar/editevent/{{event.id}}/";
		}
		
		function myDeleteEvent()
		{
			location.href = "/calendar/event/{{event.pk}}/delete/";
		}
	
		function goBack()
		{
			location.href = "{% url "calendar:month_shift" %}";
		}
	</script>

	<button type = "button" onClick = "goBack()"> Back to Calendar </button>

	<h1>{{ event.title }}</h1>

	

	{% if event.start_date %}<p><b>Start Date: </b>{{ event.start_date }}</p>{% endif %}

	{% if event.end_date %}<p><b>End Date: </b>{{ event.end_date }}</p>{% endif %}

	{% if event.sales_order %}<p><b>Sales Order: </b>{{ event.sales_order }}</p>{% endif %}

	{% if event.pick %}<p><b>Pick #: </b>{{ event.pick }}</p>{% endif %}

	{% if event.weight %}<p><b>Weight: </b>{{ event.weight }} lbs</p> {% endif %}

	{% if event.pallet %}<p><b>Pallet Count: </b>{{ event.pallet }}</p>{% endif %}

	{% if event.driver %}<p><b>Driver: </b> {{ event.driver }}</p>{% endif %}

	{% if event.phone %}<p><b>Phone: </b>{{ event.phone }}</p>{% endif %}
	
	{% if event.address_1 %}<p><b>Address 1: </b>{{ event.address_1 }}</p>{% endif %}

	{% if event.address_2 %}<p><b>Address 2 : </b>{{ event.address_2 }}</p>{% endif %}

	{% if event.city %}<p><b>City: </b>{{ event.city }}</p>{% endif %}

	{% if event.state %}<p><b>State/Province: </b>{{ event.state }}</p>{% endif %}
	
	{% if event.zipcode %}<p><b>Zip: </b>{{ event.zipcode }}</p>{% endif %}

	{% if event.description %}<p><b>Description</b>: {{ event.description }}</p>{% endif %}	

	<button type='button' onClick='myEditEvent();'> Edit Event </button>        
	<button type='button' onClick='myDeleteEvent();'> Cancel Delivery </button>	

{% endblock content %}

happenings/templates/happenings/event_month_list.html
{% extends 'happenings/middle.html' %}

{% load staticfiles happenings_tags %}

{% block content %}



<script type="text/javascript">
    function myCreateEvent() 
    {
  	location.href = '{% url "calendar:createevent" %}';     
    }

</script>

{% if cal_error %}

    {{ cal_error }}

{% endif %}



{% if not show_events %}<h1 align = center>Porcelanosa</h1>{% endif %}



<p><button type = "button" onClick = "myCreateEvent()"> Add Delivery </button></p>

<div id="event-calendar">

    {{ calendar|safe }}

</div>



{% if show_events %}

<h1 id="month-list-events-title">

    {% if cal_category and cal_tag %}

        Events in category {{ cal_category }}

        with tag = {{ cal_tag }}

    {% elif cal_category %}

        Events in {{ cal_category }}

    {% elif cal_tag %}

        Events with tag = {{ cal_tag }}

    {% else %}

        Events

    {% endif %}

</h1>



<h3>For <span id="month-and-year">{{ month_and_year }}</span></h3>

    

{% include 'happenings/partials/event_list.html' %}

{% endif %}


{% endblock content %}

happenings/templates/happenings/middle.html
{% extends 'happenings/base.html' %}